### ISSUE TITLE
Block phone numbers

### ISSUE THREAD

**Issue by pysoft13** [ubports/telephony-service#43]
Hi, would it be possible to add a blacklist of phonenumbers to block?

**Comment by Flohack74** [comment]
No, thats not easily possible out of box. you can use this Payware though: http://f-call-dev.blogspot.com/

**Comment by Fuseteam** [comment]
See for a full answer: https://github.com/ubports/dialer-app/issues/18#issuecomment-770219992

**Comment by gber** [comment]
Migrated to https://gitlab.com/ubports/development/core/telephony-service/-/issues/43
